from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field, StringConstraints
from typing import Annotated, Literal
from datetime import datetime

# Import HumanMessage to pass raw text safely into the LangGraph state
from langchain_core.messages import HumanMessage 
from orchestrator import chatbot

app = FastAPI(
    title="API Gateway / Validation Layer",
    description="Validates structural payload format and dispatches to LangChain Orchestrator.",
    version="1.2.0"
)

# Custom type annotations for robust data sanitization
CleanString = Annotated[str, StringConstraints(strip_whitespace=True, min_length=2)]
ApplicantIDString = Annotated[str, StringConstraints(strip_whitespace=True, pattern=r"^APP\d+$")]

class LoanApplicationSchema(BaseModel):
    applicant_id: ApplicantIDString
    name: CleanString
    age: int = Field(..., gt=20, le=50)
    location: CleanString
    employment_type: Literal["Full-Time", "Contract", "Freelancer"]
    gross_annual_income: float = Field(..., gt=0)
    existing_liabilities: float = Field(..., ge=0)
    credit_score: int = Field(..., ge=300, le=850)
    loan_amount: float = Field(..., gt=0)
    loan_duration_years: int = Field(..., ge=1, le=30)
    application_timestamp: datetime


def pass_to_orchestrator(data: dict) -> dict:
    """
    Constructs an analytical underwriting prompt using the validated form data,
    passes it as a HumanMessage to the LangGraph chatbot, and returns the LLM verdict.
    """
    # 1. Structure a concise system-style prompt for the underwriting model
    prompt_text = f"""
    You are an automated loan underwriting assistant. Evaluate the following applicant profile parameters and provide a clear approval or rejection verdict with a brief justification based on standard debt-to-income and credit risk variables.

    Applicant Profile Details:
    - ID: {data.get('applicant_id')}
    - Name: {data.get('name')}
    - Age: {data.get('age')}
    - Location: {data.get('location')}
    - Employment Status: {data.get('employment_type')}
    - Gross Annual Income: ${data.get('gross_annual_income'):,.2f}
    - Existing Monthly Liabilities: ${data.get('existing_liabilities'):,.2f}
    - Credit Score: {data.get('credit_score')}
    - Requested Loan Amount: ${data.get('loan_amount'):,.2f}
    - Amortization Timeline: {data.get('loan_duration_years')} Years
    - Submitted At: {data.get('application_timestamp')}
    """
    
    # 2. Package the prompt text inside LangChain's HumanMessage list as required by your ChatState
    inputs = {"messages": [HumanMessage(content=prompt_text.strip())]}  
    
    # 3. Invoke the compiled LangGraph chatbot graph
    graph_output = chatbot.invoke(inputs)
    
    # 4. Extract the last AIMessage content generated by your chat_node
    last_message = graph_output["messages"][-1]
    
    return {
        "verdict": last_message.content,
        #"model_metadata": getattr(last_message, "response_metadata", {})
    }


@app.post("/loan_approval", status_code=status.HTTP_200_OK)
async def evaluate_loan_application(application: LoanApplicationSchema):
    """
    Receives frontend payload, triggers automatic Pydantic 422 validations, 
    and hands off clean structural data to LangChain.
    """
    try:
        # Convert Pydantic object to a standard Python dictionary for LangChain compatibility
        sanitized_payload = application.model_dump()  # json request undergoes pydantic validation/transformation
        
        # Dispatch to your LangChain system
        orchestrator_response = pass_to_orchestrator(sanitized_payload)  # request passed to orchestrator
        
        return {
            "status": "Success",
            "backend_validated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "orchestrator_output": orchestrator_response
        }

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"LangChain orchestration layer failure: {str(e)}"
        )